threadtest.o: threadtest.cc \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../testoptions.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/syscalls.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/kostypes.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/pthread.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/syscalls.h
systest.o: systest.cc \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../testoptions.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/syscalls.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/kostypes.h
manythread.o: manythread.cc \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../testoptions.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/syscalls.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/kostypes.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/pthread.h \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../include/syscalls.h
kbloop.o: kbloop.cc \
 /home/ugb/lnberry/cpsc457/A2/kosClean/src/user/../testoptions.h
